### ISSUE TITLE
cm does not allow user to specify -conf as args

### ISSUE THREAD

**Issue by liulirun** [aerokube/cm#145]
I am using Linux , Ubuntu.  and have browsers.json file under  /home/griduser/config/

ls /home/griduser/config/ -lrt
-rw-rw-r-- 1 griduser griduser  331 Mar  9 15:23 browsers.json.bk
-rw-rw-r-- 1 griduser griduser  327 Mar 14 09:00 browsers.json

also I have cm downloaded. because I only cares for chrome, so I do not want to start all the browsers. So i create this browsers.json like this: 

{
    "chrome": {
        "default": "64.0",
        "versions": {
            "64.0": {
                "image": "selenoid/chrome:64.0",
                "port": "4444",
                "path": "/",
				"tmpfs": {"/tmp": "size=2048m"},
				"env" : ["SCREEN_RESOLUTION=1600x1380x24"]
            }
        }
    }
}

when I run below 
./cm selenoid start --config-dir /home/griduser/config --args "-conf /home/griduser/config -limit 4 -retry-count 2 -session-attempt-timeout 1800s -timeout 2m"

, the container keeps restarting.  error: 
2018/03/17 23:49:22 [-] [INIT] [Loading configuration files...]
2018/03/17 23:49:22 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /home/griduser/config: no such file or directory]

If I do docker inspect, the `binds` part: 
            "Binds": [
                "/home/griduser/config:/etc/selenoid:ro",
                "/home/griduser/config/video:/opt/selenoid/video",
                "/var/run/docker.sock:/var/run/docker.sock"
            ],

============================================

I used to use cmd without specifying -conf in --args.
./cm selenoid start --config-dir /home/griduser/config --args "-limit 4 -retry-count 2 -session-attempt-timeout 1800s -timeout 2m"

This starts the container, but when I do docker inspect

    {
        "Id": "c4eb1ae2aa27f9e50d1e8d316921725c55107c135418c72e1a1dd266bf4c8cc1",
        "Created": "2018-03-17T23:52:44.37038876Z",
        "Path": "/usr/bin/selenoid",
        "Args": [
            "-limit",
            "4",
            "-retry-count",
            "2",
            "-session-attempt-timeout",
            "1800s",
            "-timeout",
            "2m",
            "-conf",
            "/etc/selenoid/browsers.json",
            "-video-output-dir",
            "/opt/selenoid/video/"

notice the default -conf is /etc/selenoid/browsers.json, which is not what i want. 
because I do not want to specify the video-output-dir, nor I do not want to have vnc enabled by default. 

Please help.

**Comment by vania-pooh** [comment]
@liulirun this is how it works:
1) `--config-dir` flag of `cm` defines a directory on the `host machine` where all configuration files are generated and then stored. So passing `--config-dir /home/griduser/config` is correct.
2) Selenoid `-conf` flag defines `path` to `browsers.json` configuration file. So far as Selenoid is being run in Docker container - host machine directory needs to be mounted `inside container`. This stuff is currently hard-coded in [cm](https://github.com/aerokube/cm/blob/master/selenoid/docker.go#L637-L638) because this is the default value in Selenoid [Dockerfile](https://github.com/aerokube/selenoid/blob/master/Dockerfile). So changing `-conf` is useless. In order to move directory in the host machine - you only have to specify `--config-dir` and it should work.

**Comment by liulirun** [comment]
kk, I will close this one. 
Thank you
