### ISSUE TITLE
Browers.json file being saved outside of selenoid docker container

### ISSUE THREAD

**Issue by damiensprinkle** [aerokube/cm#328]
I'm trying to setup selenoid on an azure build agent using the following commands
```
cd $(System.DefaultWorkingDirectory)/Repo/Base/Scripts/
chmod +x cm 
./cm selenoid start --vnc --port 4444 --force
```

This seems to work, all the brower images are downloaded etc. However when I look at the container logs I see the following message 
```
2023-03-09T18:46:41.958042395Z 2023/03/09 18:46:41 [-] [INIT] [/usr/bin/selenoid: browsers config: read error: open /etc/selenoid/browsers.json: no such file or directory]
```
After looking into it further I can see the browsers.json file is being saved into a different home directory on the build agent 
```
> Configuration saved to /home/build_azpcontainer/.aerokube/selenoid/browsers.json
```

Has anyone seen this before or have any idea why this is happening?

Note: I am using the latest version of the linux_amd64 cm

**Comment by vania-pooh** [comment]
@damiensprinkle containers are stateless, all state should be hosted outside of containers. So Selenoid when running in container is always expecting config file to be mounted to `/etc/selenoid/browsers.json` inside container. Outside of container CM tool is usually generating such file to `~/.aerokube/selenoid/browsers.json`. So that's the expected behavior. Make sure you really have such file on filesystem.

**Comment by damiensprinkle** [comment]
@vania-pooh Yeah the folder structure exists and the file is created at ~/.aerokube/selenoid/browsers.json in my case "home" is 
"/home/build_azpcontainer"

I ran "cat ~/.aerokube/selenoid/browsers.json" and the browsers.json file contents were returned as expected . So if the file exists in the correct location, why would it not be mounted inside the container?

**Comment by vania-pooh** [comment]
@damiensprinkle probably some security settings in Docker or SELinux or similar stuff.
