### ISSUE TITLE
Docker for Windows/Docker Toolbox - Can't run cm start  selenoid/selenoid-ui

### ISSUE THREAD

**Issue by unickq** [aerokube/cm#81]
- CM 1.2.4
- Windows 10
- Docker for Windows 17.06.2 / Docker Toolbox 17.05

> Failed to start: failed to create container: Error response from daemon: invalid environment variable: =::=::\

**Comment by azee** [comment]
+1
Docker: Version 17.06.2-ce-win27 (13194)
Window 10

**Comment by vania-pooh** [comment]
After some tests understood that this is `os.Environ()` call that passes all Windows environment variables that causes the issue. Searching the way to fix this.

**Comment by xpinjection** [comment]
I got the same issue. Tried to play with different options for volume mappings but also without any success. It prepends my Windows path with /root/, so I got something like '/root/c:/temp/selenoid/.aerokube/'. It would be great if in official guide you place realistic example for Windows, because at the moment some pieces looks strange: -v /var/run/docker.sock:/var/run/docker.sock doesn't make any sense for Windows.

**Comment by vania-pooh** [comment]
@xpinjection agreed.

**Comment by vania-pooh** [comment]
This should have been fixed in #84. Could anybody try whether it now works? Attaching archives with binaries to test (Github does not allow to upload `exe`).
[cm_windows_386.zip](https://github.com/aerokube/cm/files/1370601/cm_windows_386.zip)
[cm_windows_amd64.zip](https://github.com/aerokube/cm/files/1370602/cm_windows_amd64.zip)

**Comment by AnisimovAleksandr** [comment]
Yep! It's working )))

`c:\servers\selenoid>cm selenoid status
2017/10/11 09:39:54 Using Docker...
2017/10/11 09:39:54 registry.ping url=https://registry.hub.docker.com/v2/
2017/10/11 09:39:55 Using Selenoid image: aerokube/selenoid:1.3.7 (sha256:9a093189792ba7f389c0de26d3a686c4b10b5dfdf9cc9dd023d546f1aee1e6c3)
2017/10/11 09:39:55 Selenoid configuration directory is C:\Users\<user folder>\.aerokube\selenoid
2017/10/11 09:39:55 Selenoid configuration file is C:\Users\<user folder>\.aerokube\selenoid\browsers.json
2017/10/11 09:39:55 Selenoid container is running: selenoid (67e3f53abfe2d6c0434a508ab9e6c6929a0abc6c55dfbc61b9c1d05b9a832241)`

**Comment by vania-pooh** [comment]
Good, closing then.

**Comment by vania-pooh** [comment]
This was released as https://github.com/aerokube/cm/releases/tag/1.2.5.

**Comment by vania-pooh** [comment]
More documentation will be added in https://github.com/aerokube/selenoid/issues/239.
